### PR TITLE
Add in the Recomb function.

### PR DESCRIPTION
**Pull request by fromkeith**
Adding in a basci "Recomb" #164

### CODE REVIEW

**Comment by lovell** [comment]
Hello, thanks for this, I'll be able to take a closer look in the next day or so.

In the meantime it might be worth adding a test for an PNG image with an alpha transparency e.g. `inputPngWithTransparency` to ensure this works also.

**Comment by fromkeith** [comment]
Sure!

I think the Alpha channel may cause some issues, since the current code is hardcoded for a 3x3 matrix. It doesn't look like 'channels' is necessarily set until pipeline.cc. So I can either:

* Set the identity for Alpha, and force a 3x3 matrix input.
* Or Allow 4x4 matrices, but throw away the extra col/row if no alpha channel is found in pipeline.cc

I'll start with the first, but it shouldn't be too much work to go the route of the second if you prefer.

**Comment by lovell** [comment]
Thanks, option 1 sounds like the right approach.

**Comment by lovell** [comment]
I've merged this in commit 541e710 - the RGBA example wasn't quite right so I took the liberty of simplifying that logic. Thanks again for this PR - it will be included in the next release, probably v0.21.1.

**Pull request closed without merging**
