### PR TITLE
Arm64 support

### PR DESCRIPTION
**Pull request by Stoyvo**
Add support for MacOS Arm64 and Windows Arm64

Fixes: https://github.com/lovell/sharp/issues/3936

### CODE REVIEW

**Comment by lovell** [comment]
Hi, thanks for the PR. Prebuilt ARM64 binaries are already provided for macOS and Linux. Unfortunately there are no CI providers that currently provide support for ARM64 on Windows. If you know of one, please let me know.

I'll close this PR as it won't work on the existing CI setup.

**Comment by tstoyanovski-humi** [comment]
@lovell are you using github runners?
https://github.com/actions/runner/pull/2022

**Comment by lovell** [comment]
@tstoyanovski-humi The issue you've linked to relates to software support. What we need is someone offering hosted hardware, for free, ideally GitHub Actions itself as that's what we currently use for Windows on amd64.

**Comment by jhholm** [comment]
Not sure if this is the correct place, but it seems that ARM hosted runners are finally available in GitHub

https://blogs.windows.com/windowsdeveloper/2025/04/14/github-actions-now-supports-windows-on-arm-runners-for-all-public-repos/

**Comment by lovell** [comment]
For Windows ARM64 support please see https://github.com/lovell/sharp-libvips/issues/238

**Pull request closed without merging**
