### PR TITLE
Check loaded bindings not only on Windows

### PR DESCRIPTION
**Pull request by marvinroger**

### CODE REVIEW

**Comment by lovell** [comment]
Perhaps we should only additionally show this help when the error message mentions a symbol-related problem?
```js
if (process.platform === 'win32' || /symbol/.test(err.message)) { ...
```

**Comment by marvinroger** [comment]
I rebased and amended the commit with your suggestion, therefore I force-pushed to have a single commit as specified in the CONTRIBUTING.md

**Comment by lovell** [comment]
C'est super, merci Marvin.

**Comment by marvinroger** [comment]
Merci à toi !

**Pull request merged**
