### PR TITLE
Adapted alpine install command

### PR DESCRIPTION
**Pull request by BorntraegerMarc**
To not use edge version anymore but fixed version (more stable)

### CODE REVIEW

**Comment by lovell** [comment]
Thanks for the PR. Is the `apk update` command required given the `--update` flag is passed to `apk add`?

**Comment by BorntraegerMarc** [comment]
> Thanks for the PR. Is the `apk update` command required given the `--update` flag is passed to `apk add`?

It is actually not. Thanks for critically reviewing my changes. I have basically no experience with alpine linux and kinda tried my way around until I found this solution.

Adapted the docs.

**Comment by lovell** [comment]
Thanks, likewise we probably shouldn't be telling people to run `apk upgrade`. Please can this include only the salient `apk add ...` command.

**Comment by BorntraegerMarc** [comment]
> can this include only the salient apk add ... command

Unfortunately not. I've tried with only the apk add command and this is the error I'm getting:
```
ERROR: unsatisfiable constraints:
  musl-1.1.19-r10:
    breaks: musl-dev-1.1.22-r3[musl=1.1.22-r3]
    satisfies: musl-utils-1.1.19-r10[musl=1.1.19-r10] musl-utils-1.1.19-r10[so:libc.musl-x86_64.so.1] gettext-0.19.8.1-r4[so:libc.musl-x86_64.so.1] orc-0.4.29-r0[so:libc.musl-x86_64.so.1]
               pkgconf-1.6.1-r1[so:libc.musl-x86_64.so.1] glib-dev-2.60.4-r0[so:libc.musl-x86_64.so.1] libblkid-2.33.2-r0[so:libc.musl-x86_64.so.1] libfdisk-2.33.2-r0[so:libc.musl-x86_64.so.1]
               gcc-8.3.0-r0[so:libc.musl-x86_64.so.1] g++-8.3.0-r0[so:libc.musl-x86_64.so.1] libjpeg-turbo-2.0.2-r0[so:libc.musl-x86_64.so.1] libpng-1.6.37-r1[so:libc.musl-x86_64.so.1]
               libxslt-1.1.33-r1[so:libc.musl-x86_64.so.1] python3-3.7.3-r0[so:libc.musl-x86_64.so.1] busybox-1.28.4-r1[so:libc.musl-x86_64.so.1] giflib-5.1.9-r0[so:libc.musl-x86_64.so.1]
               binutils-2.32-r0[so:libc.musl-x86_64.so.1] sqlite-libs-3.28.0-r0[so:libc.musl-x86_64.so.1] libuuid-2.33.2-r0[so:libc.musl-x86_64.so.1] mpfr3-3.1.5-r1[so:libc.musl-x86_64.so.1]
               ncurses-libs-6.1_p20190518-r0[so:libc.musl-x86_64.so.1] expat-2.2.7-r0[so:libc.musl-x86_64.so.1] fftw-single-libs-3.3.8-r0[so:libc.musl-x86_64.so.1]
               fftw-double-libs-3.3.8-r0[so:libc.musl-x86_64.so.1] gettext-asprintf-0.19.8.1-r4[so:libc.musl-x86_64.so.1] libgcrypt-1.8.4-r2[so:libc.musl-x86_64.so.1]
               vips-8.8.0-r0[so:libc.musl-x86_64.so.1] gdbm-1.13-r1[so:libc.musl-x86_64.so.1] libstdc++-8.3.0-r0[so:libc.musl-x86_64.so.1] libbz2-1.0.6-r7[so:libc.musl-x86_64.so.1]
               file-5.37-r0[so:libc.musl-x86_64.so.1] libwebp-1.0.2-r0[so:libc.musl-x86_64.so.1] isl-0.18-r0[so:libc.musl-x86_64.so.1] mpc1-1.1.0-r0[so:libc.musl-x86_64.so.1]
               libunistring-0.9.10-r0[so:libc.musl-x86_64.so.1] libmagic-5.37-r0[so:libc.musl-x86_64.so.1] libxml2-utils-2.9.9-r2[so:libc.musl-x86_64.so.1] libexif-0.6.21-r3[so:libc.musl-x86_64.so.1]
               pcre-8.43-r0[so:libc.musl-x86_64.so.1] orc-dev-0.4.29-r0[so:libc.musl-x86_64.so.1] libffi-3.2.1-r6[so:libc.musl-x86_64.so.1] zlib-1.2.11-r1[so:libc.musl-x86_64.so.1]
               libmount-2.33.2-r0[so:libc.musl-x86_64.so.1] glib-2.60.4-r0[so:libc.musl-x86_64.so.1] libgomp-8.3.0-r0[so:libc.musl-x86_64.so.1] apk-tools-2.10.1-r0[so:libc.musl-x86_64.so.1]
               libintl-0.19.8.1-r4[so:libc.musl-x86_64.so.1] readline-8.0.0-r0[so:libc.musl-x86_64.so.1] libtiffxx-4.0.10-r1[so:libc.musl-x86_64.so.1] make-4.2.1-r2[so:libc.musl-x86_64.so.1]
               lcms2-2.9-r1[so:libc.musl-x86_64.so.1] libgpg-error-1.36-r2[so:libc.musl-x86_64.so.1] libressl2.7-libcrypto-2.7.4-r0[so:libc.musl-x86_64.so.1] libgcc-6.4.0-r9[so:libc.musl-x86_64.so.1]
               libssl1.1-1.1.1c-r0[so:libc.musl-x86_64.so.1] alpine-baselayout-3.1.0-r0[so:libc.musl-x86_64.so.1] libcrypto1.1-1.1.1c-r0[so:libc.musl-x86_64.so.1]
               libpcre16-8.43-r0[so:libc.musl-x86_64.so.1] libatomic-8.3.0-r0[so:libc.musl-x86_64.so.1] xz-libs-5.2.4-r0[so:libc.musl-x86_64.so.1] libpcre32-8.43-r0[so:libc.musl-x86_64.so.1]
               libxml2-2.9.9-r2[so:libc.musl-x86_64.so.1] scanelf-1.2.3-r0[so:libc.musl-x86_64.so.1] fftw-long-double-libs-3.3.8-r0[so:libc.musl-x86_64.so.1] gmp-6.1.2-r1[so:libc.musl-x86_64.so.1]
               gettext-libs-0.19.8.1-r4[so:libc.musl-x86_64.so.1] libsmartcols-2.33.2-r0[so:libc.musl-x86_64.so.1] tiff-4.0.10-r1[so:libc.musl-x86_64.so.1]
               libressl2.7-libssl-2.7.4-r0[so:libc.musl-x86_64.so.1] libpcrecpp-8.43-r0[so:libc.musl-x86_64.so.1]
```

**Comment by lovell** [comment]
That message relates to the need to upgrade the underlying musl libc upon which pretty much everything in Alpine depends rather than being specific to the vips package, so I'm not still not quite sure doing so belongs in the sharp docs.

**Comment by BorntraegerMarc** [comment]
Right. So you're suggesting to only upgrade musl? Do you know how to do that?

**Comment by lovell** [comment]
I think a few simplification are possible:

* Using Alpine 3.10 instead of Edge means we don't need to specify the main repository and no longer require the `--update-cache` flag.
* The `vips-dev` package now lists `fftw-dev` as a dep.
* Adding `--upgrade` as a flag will only upgrade `vips-dev`, if present.

Putting it together gives:

```sh
apk add --upgrade --no-cache vips-dev build-base --repository https://alpine.global.ssl.fastly.net/alpine/v3.10/community/
```

I've tested this via:
```sh
$ docker run -i -t --rm alpine:3.10 apk add --upgrade --no-cache vips-dev fftw-dev build-base --repository https://alpine.global.ssl.fastly.net/alpine/v3.10/community/
```
Are you able to check this works for you?

**Comment by lovell** [comment]
Updated and landed in https://github.com/lovell/sharp/commit/0e66454fe4e5318362d06cfa897ad4c149277ad3 - thanks for the PR!

**Comment by BorntraegerMarc** [comment]
Hi @lovell

Sorry for getting back so late at you. I wanted to test your suggestion this week. Running your code in `node:8.13.0-alpine` throws me an error:
```
Step 8/14 : RUN apk add --upgrade --no-cache vips-dev build-base --repository https://alpine.global.ssl.fastly.net/alpine/v3.10/community/
 ---> Running in 5b63051f3493
fetch https://alpine.global.ssl.fastly.net/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  pc:fftw3 (missing):
    required by: vips-dev-8.8.0-r0[pc:fftw3]
                 vips-dev-8.8.0-r0[pc:fftw3]
                 vips-dev-8.8.0-r0[pc:fftw3]
```

**Comment by lovell** [comment]
The `node:8.13.0-alpine` image is based on Alpine 3.8 rather than 3.10.

**Comment by BorntraegerMarc** [comment]
also running 
```
apk upgrade && \
apk add --update --no-cache --update-cache vips-dev fftw-dev build-base \
    --repository https://alpine.global.ssl.fastly.net/alpine/v3.8/community/ \
    --repository https://alpine.global.ssl.fastly.net/alpine/v3.8/main
```

throws me the error:
```
ERROR: unsatisfiable constraints:
  vips-dev (missing):
    required by: world[vips-dev]
```

Only my solution worked so far. Should this lib support alpine node 8?

**Comment by lovell** [comment]
sharp currently supports Node 8 on Alpine (and pretty much any other OS).

The problem you're seeing is that Alpine 3.8 does not provide a vips-dev package.

**Pull request closed without merging**
