### PR TITLE
Add support for a single shared library (#2535)

### PR DESCRIPTION
**Pull request by kleisauke**
This PR adds supports for a single shared libvips library (i.e. `libvips.so.42` statically linked into `libvips-cpp.so.42`) as described in issue https://github.com/lovell/sharp/issues/2535 and PR https://github.com/lovell/sharp-libvips/pull/81.

Testing can be done with:
```bash
rm ~/.npm/_libvips/libvips-8.10.5-linux-x64.tar.br
SHARP_DIST_BASE_URL="https://github.com/kleisauke/libvips-packaging/releases/download/v8.10.5-single-shared/" \
  npm install kleisauke/sharp#single-shared
```

Depends on: https://github.com/lovell/sharp-libvips/pull/81.

(the last commit must be reverted before merging)

### CODE REVIEW

**Comment by kleisauke** [comment]
Some unit tests on Linux ARM64v8 seems to be failing. This worked yesterday without any problems, see:
https://travis-ci.org/github/kleisauke/sharp/builds/756278183

**Comment by lovell** [comment]
> Some unit tests on Linux ARM64v8 seems to be failing.

I switched to parallel processes for the unit tests but it looks like the ARM64 VMs provided by Travis use LXD and might over-commit CPU and/or RAM, leading to random segfaults. They've got some new Graviton-based VMs but those are only on the paid-for service. I expect Travis to go away fairly soon so it might be time to invest in a Raspberry Pi 4 as a self-hosted runner.

**Comment by dennisameling** [comment]
@lovell you can [apply for free OSS credits](https://travis-ci.com/plans) on the new travis-ci.com, have you tried that already? Then you'd be able to use the new Graviton-based VMs.

image

You can just email them at support [at] travis-ci [dot] com to apply for credits 👍🏼

**Comment by lovell** [comment]
@dennisameling I can try after my Travis account is switched from their .org to .com site, which I have wisely resisted for as long as possible. I've heard from other OSS maintainers that there's nothing available beyond the initial offering, which I estimate would be enough for fewer than 40 builds in total. :sad_panda:

**Comment by tomByrer** [comment]
> invest in a Raspberry Pi 4 as a self-hosted runner

I thought of that myself, but one can find very powerful Android Phones for under $100 (eg new Samsung S01 for $70 at local Wal*Mart) then root & put Linux on it.

**Comment by lovell** [comment]
Landed via commit https://github.com/lovell/sharp/commit/4fc1d0c9007ba6e38edb57f8a0dc5b22de53f31f

**Pull request closed without merging**
