### PR TITLE
Linux Dockerfile: Use Debian Wheezy as the base image

### PR DESCRIPTION
**Pull request by papandreou**
Tested with Debian Wheezy and Ubuntu Vivid.

### CODE REVIEW

**Comment by lovell** [comment]
Great, thanks Andreas. Inspired by this I might also test with Debian 6 as that should allow support for RHEL/Centos 6.

**Comment by papandreou** [comment]
Thanks a lot!

**Comment by lovell** [comment]
@papandreou I've gone a quick test with Debian 6 inside a Docker container (on Ubuntu 14.04) but it keeps freezing the CPU, so probably a no-go without a lot of extra effort.

**Comment by papandreou** [comment]
Bummer, but cool that you tried it out. I'm still happy that Wheezy fell on the right side of the sweet spot :)

**Pull request merged**
