### PR TITLE
feat: exposing vips_affine operation

### PR DESCRIPTION
**Pull request by guillevc**
Exposes `vips_affine` operation as discussed in #2095. Supports making an affine transformation from a 2x2 matrix and optional offsets, background color and any supported interpolator.

This is my first PR to this project so please propose any changes or ask any questions.

Here is the proposed API implemented in this PR:
## affine

Perform an affine transform on an image. This operation will always occur after resizing, extraction and rotation, if any.

You must provide a 2x2 affine transformation matrix.
By default, new pixels are filled with a black background. You can provide a background color with the `background` option.
A particular interpolator may also be specified. Set the `interpolator` option to an attribute of the `sharp.interpolator` Object e.g. `sharp.interpolator.nohalo`.

The transform is:

-   X = `matrix[0, 0]` \* (x + `idx`) + `matrix[0, 1]` \* (y + `idy`) + `odx`
-   Y = `matrix[1, 0]` \* (x + `idx`) + `matrix[1, 1]` \* (y + `idy`) + `ody`

where:

-   x and y are the coordinates in input image.
-   X and Y are the coordinates in output image.
-   (0,0) is the upper left corner.

### Parameters

-   `matrix` **[Array][7]&lt;[Array][7]&lt;[number][1]>>** 2x2 affine transformation matrix
-   `options` **[Object][2]?** if present, is an Object with optional attributes.
    -   `options.background` **([String][3] \| [Object][2])** parsed by the [color][4] module to extract values for red, green, blue and alpha. (optional, default `"#000000"`)
    -   `options.idx` **[Number][1]** input horizontal offset (optional, default `0`)
    -   `options.idy` **[Number][1]** input vertical offset (optional, default `0`)
    -   `options.odx` **[Number][1]** output horizontal offset (optional, default `0`)
    -   `options.ody` **[Number][1]** output vertical offset (optional, default `0`)
    -   `options.interpolator` **[String][3]** interpolator (optional, default `sharp.interpolators.bicubic`)

### Examples

```javascript
const pipeline = sharp()
  .affine([[1, 0.3], [0.1, 0.7]], {
     background: 'white',
     interpolate: sharp.interpolators.nohalo
  })
  .toBuffer((err, outputBuffer, info) => {
     // outputBuffer contains the transformed image
     // info.width and info.height contain the new dimensions
  });

inputStream
  .pipe(pipeline)
  .pipe(outputStream);
```
## interpolators

An Object containing the available interpolators and their proper values

Type: [string][2]

### nearest

[Nearest neighbour interpolation][3]. Suitable for image enlargement only.

### bilinear

[Bilinear interpolation][4]. Faster than bicubic but with less smooth results.

### bicubic

[Bicubic interpolation][5] (the default).

### locallyBoundedBicubic

[LBB interpolation][6]. Prevents some "[acutance][7]" but typically reduces performance by a factor of 2.

### nohalo

[Nohalo interpolation][8]. Prevents acutance but typically reduces performance by a factor of 3.

### vertexSplitQuadraticBasisSpline

[VSQBS interpolation][9]. Prevents "staircasing" when enlarging.

### CODE REVIEW

**Comment by lovell** [comment]
Thank you for the PR, I'm currently preparing sharp v0.26.0 for release, then will come back to this to review it properly.

**Comment by lovell** [comment]
Hi, I removed the `zoom` WIP branch and GitHub appears to have auto-closed this PR and won't let me change the destination branch or reopen it :(

Please can you re-open using the `master` branch.

**Comment by guillevc** [comment]
@lovell no problem. Here's the re-opened PR: https://github.com/lovell/sharp/pull/2336

**Comment by banli17** [comment]
😊 When will this feature be available

**Pull request closed without merging**
