### PR TITLE
Upgrade to prebuild-install 6.0.0

### PR DESCRIPTION
**Pull request by medianick**
Adds support for npm 7; see release notes for [6.0.0](https://github.com/prebuild/prebuild-install/releases/tag/v6.0.0).

See discussion at #2415 for stack traces, examples, etc.

### CODE REVIEW

**Review by lovell — APPROVED** [review]
Thanks Nick, I'll merge this as part of v0.27.0, probably in about a week.

**Comment by abastien** [comment]
Hello, when will version 0.27 be released please I need this MR ;)

**Comment by nstepien** [comment]
@lovell Would you consider doing a `v0.26.3` patch release?

**Comment by lovell** [comment]
@nstepien Quite possibly, this PR will be included if so.

**Comment by lovell** [comment]
Thanks, this will be in v0.26.3.

**Comment by lovell** [comment]
v0.26.3 now available

**Pull request merged**
