### PR TITLE
Overlay from buffer and overlay scaling

### PR DESCRIPTION
**Pull request by chrisriley**
Hi Lovell,

We had a use case for loading overlays from a buffer and also needed to be able to scale the overlay to a ratio of the main scaled image. These patches allow for overlays to be loaded from a node.js buffer in addition to a file and add `overlayGravity()`, `overlayRatio()`, and `interpolateOverlayWith()` methods. I wanted to put this out there in case anyone else might find it useful.

Regards,
Chris

### CODE REVIEW

**Comment by lovell** [comment]
Thanks Chris, this is great start on the work required for #239. I need to think a bit more about the public API for this, e.g. does this need its own interpolator?

I'm currently moving sharp to use libvips' new C++ bindings as part of #299 and will take a closer look at how to manually merge in your work using its newer API once that's done. Cheers!

**Comment by chrisriley** [comment]
Hi Lovell, I have an updated pull request (now with unit tests! :smile:) that includes a two additional methods, `overlaySize()` and `padOverlay()`. `overlaySize()` takes a width and height parameter and is used for exact control of the resized overlay, as opposed to `overlayRatio()` (which is still in there but is trumped by `overlaySize()` if both are used. `padOverlay()` accepts a boolean and adds a minimal amount of padding to the overlay's bounding box to keep it from running into the edges of the main image.

As for overlay's having their own interpolator, that was something I added because I wanted to be able to use bicubic for the background image and bilinear for the overlay.

Thanks!

**Comment by lovell** [comment]
I've updated #239 with my thoughts on the API additions to improve the existing `overlayWith` method.

I'm not keen on including the ability to resize/interpolate/ratio the overlay image separately given there are already methods to achieve this. There are so many edge cases to resizing that I'd rather provide one way to do this.

The ability to pad an image, overlay or otherwise, should be satisfied by the long-standing feature request of #128.

The migration to the vips8 C++ bindings is almost complete. The [mind](https://github.com/lovell/sharp/tree/mind) branch contains this work and will form the basis of the future v0.13.0 release. By way of example, look how much simpler the internal [Composite](https://github.com/lovell/sharp/blob/mind/src/operations.cc#L14) method has become :)

if you'd like to have a go at getting the API outlined in #239 working with the C++ bindings on the `mind` branch, that would be most fantastic. I'm also happy to adapt and merge the work you've done so far here in this PR.

Most importantly, thanks again @chrisriley for all your ideas, code and time on this feature.

**Comment by SimonSelg** [comment]
Hey @chrisriley,

Your code seems to be missing an 

```c
#include <math.h>
```

in `operations.c`, otherwise `round` (line 30 and 31) is not defined. Thanks for the code - you saved me some hours implementing the same functionality!

**Comment by lovell** [comment]
I'm going to close this PR now as the features missing from sharp have now been reworked as #239, with the exception of `pad` covered by #128. Thanks again @chrisriley for all your work on this!

**Pull request closed without merging**
