### PR TITLE
Arraybuffer

### PR DESCRIPTION
**Pull request by kapouer**
Supercedes https://github.com/lovell/sharp/pull/3546

### CODE REVIEW

**Comment by kapouer** [comment]
@lovell voilà. Sorry for the mess with the previous PR.

**Comment by lovell** [comment]
Please can you add `ArrayBuffer` to the TypeScript definitions, approximately here:

https://github.com/lovell/sharp/blob/4798d9da641b939a4e26a99d49342728676f4442/lib/index.d.ts#L29-L32

**Comment by kapouer** [comment]
Forgot about that. Done

**Comment by lovell** [comment]
Merci beaucoup Jérémy!

**Pull request merged**
