### PR TITLE
Allow for negative top/left offsets in composite overlays

### PR DESCRIPTION
**Pull request by christianflintrup**
Composite overlays can be negatively offset, as requested in #1160.

Potentially breaking changes:

- A top or left offset value of -1 will no longer mean that the value is not set, but will now be an actual offset of -1.
- Only either of top and left offsets are now required; not both.

### CODE REVIEW

**Comment by lovell** [comment]
Thank you very much for this PR Christian, I'll try to make time to review it properly next week.

Does this approach still support composition at the top-left corner, i.e. top=0 and left=0? It might be worth adding this as a test case either way.

**Comment by lovell** [comment]
Thanks to your PR, I noticed the thresholds of some of the existing composite offset unit tests were not protecting us well enough against regression. 

Please can you rebase this PR against the latest upstream master to pick up commit 1717173 to check the updated "zero offset" test case.

**Comment by CurosMJ** [comment]
👍

**Comment by ariklevin** [comment]
Any plans to approve this 1?

**Comment by lovell** [comment]
@christianflintrup Please can you rebase this PR to pick up the newer tests mentioned in https://github.com/lovell/sharp/pull/2071#issuecomment-586578782

**Comment by CurosMJ** [comment]
@christianflintrup @lovell I'll be happy to fix this, waiting for a few days for the original author to rebase, if not I will open up another PR. 😄

Thanks!

**Comment by lovell** [comment]
Closing in favour of #2391 but thank you very much @christianflintrup for starting things - you will get credit when it's merged.

**Pull request closed without merging**
