### PR TITLE
Fix for orientation values 1-8

### PR DESCRIPTION
**Pull request by jtobinisaniceguy**
Included mocha locally to facilitate VS2015 with NTVS 1.1

### CODE REVIEW

**Comment by lovell** [comment]
Hello John, thanks for this fix for #382.

Are you able to update the relevant values in the [withMetadata docs](https://github.com/lovell/sharp/blob/master/docs/api.md#withmetadatametadata) also?

I'd very much prefer not to introduce `mocha` to `dependencies`; test dependencies belong in the `devDependencies` section. If there's a specific platform this doesn't work on, I suggest the use of `npm install -g mocha`.

**Comment by jtobinisaniceguy** [comment]
Will do today

**Comment by jtobinisaniceguy** [comment]
Will push later today

**Comment by jtobinisaniceguy** [comment]
Interesting if I have mocha installed locally, all test pass
When installed globally I get this
  1) Input/output Handle Stream to Stream error :
     Uncaught Error: EPERM: operation not permitted, open 'C:\Users\User Name\Documents\OpenSource\Sharp\test\fixtures\output.jpg'
      at Error (native)

Some funny with mocha I believe

**Comment by lovell** [comment]
Sorry, I think I may have confused things. Please leave `mocha` where it is, in `devDependencies`. This PR should not require any changes to `package.json`.

Thanks for updating the docs. Please can you rebase against upstream/master and squash into a single commit and we can get this into the forthcoming v0.14.0.

**Comment by lovell** [comment]
Thanks for the changes, looking great. Are you able to squash into a single commit? I notice the commits are from (or at least are linked to) a different Github account - is this intentional?

**Comment by lovell** [comment]
Landed in ebfc897, thank you!

**Pull request closed without merging**
