### PR TITLE
WIP Using vips_resize and less aggressive shrink_on_load

### PR DESCRIPTION
**Pull request by jardakotesovec**
Here is my attempt to make progress on #848.

It consists of two adjustments. One is to use image.resize() instead of directly image.reduce() and image.shrink(). And second is leaving at least a factor of two for the final resize step for jpeg load on shrink, which is what vipsthumbnail does and without it I was still getting shifted results.

Only with combination of these two adjustments I was getting consistent position and look when generating small thumbnails from big resolutions.

My test is basically resizing from 24 different resolutions to target resolution of 35x25.

I attach zip of result images of original sharp implementation and after these adjustments to illustrate the difference.

[res_jpegshrink_vipsresize.zip](https://github.com/lovell/sharp/files/1317236/res_jpegshrink_vipsresize.zip)
[res_original.zip](https://github.com/lovell/sharp/files/1317237/res_original.zip)

These changes likely has some performance impact - so next step would be to see if performance is acceptable before we decide what to do and final clean up would be necessary. There are currently 3 failing tests - visually they seem ok (just small shift which breaks threshold).. or better than previous.

Do you have some benchmark to tell objectively how significant is it?

### CODE REVIEW

**Comment by lovell** [comment]
Hello, thank you for starting work on this Jarda, good to learn this is solving the problem you reported.

If you didn't see them, there are some (comparative, but still useful here) performance tests in https://github.com/lovell/sharp/tree/master/test/bench

**Comment by jardakotesovec** [comment]
Tried the benchmarks. Results look very similar for original vs vips_resize. Only significant jump is the reducing the shrinkOnLoad optimization, which can makes big difference in some situations in benchmark it show even double performance difference. 

Personally I would still prefer to stick with compromise and use shrinkOnLoad always just with lower factors, which still can help a lot when generating small resolutions rather than having option to switch it on/off as there is significantly higher chance of creating inconsistent results as its purely luck how exactly source resolution fits to the n^2 factor, therefore its tricky for developers to decide if to switch it on or off. In the generated images I provided initially you can see that some images looks significantly different (not just the position) while the source resolution just slightly changed.

@lovell Whats your opinion?  If I get green light I would clean up the code to make this PR usable.

Original:
```
jpeg sharp-buffer-file x 14.53 ops/sec ±1.18% (67 runs sampled)
jpeg sharp-buffer-buffer x 14.92 ops/sec ±1.00% (69 runs sampled)
jpeg sharp-file-file x 14.52 ops/sec ±1.00% (68 runs sampled)
jpeg sharp-stream-stream x 14.28 ops/sec ±1.14% (66 runs sampled)
jpeg sharp-file-buffer x 14.60 ops/sec ±0.86% (68 runs sampled)
jpeg sharp-promise x 14.72 ops/sec ±1.12% (68 runs sampled)
operations sharp-sharpen-mild x 13.58 ops/sec ±1.16% (64 runs sampled)
operations sharp-sharpen-radius x 9.42 ops/sec ±0.89% (47 runs sampled)
operations sharp-blur-mild x 13.86 ops/sec ±0.91% (65 runs sampled)
operations sharp-blur-radius x 12.59 ops/sec ±1.14% (60 runs sampled)
operations sharp-gamma x 5.22 ops/sec ±0.63% (29 runs sampled)
operations sharp-normalise x 9.05 ops/sec ±1.11% (46 runs sampled)
operations sharp-greyscale x 7.69 ops/sec ±0.80% (40 runs sampled)
operations sharp-greyscale-gamma x 2.88 ops/sec ±0.85% (18 runs sampled)
operations sharp-progressive x 12.62 ops/sec ±1.02% (60 runs sampled)
operations sharp-without-chroma-subsampling x 13.87 ops/sec ±0.99% (65 runs sampled)
operations sharp-rotate x 14.23 ops/sec ±1.01% (66 runs sampled)
operations sharp-without-simd x 11.03 ops/sec ±0.77% (54 runs sampled)
operations sharp-sequentialRead x 14.47 ops/sec ±1.04% (67 runs sampled)
operations sharp-crop-entropy x 14.79 ops/sec ±0.97% (68 runs sampled)
operations sharp-crop-attention x 14.90 ops/sec ±0.97% (69 runs sampled)
kernels sharp-cubic x 15.30 ops/sec ±1.14% (71 runs sampled)
kernels sharp-lanczos2 x 15.12 ops/sec ±0.95% (70 runs sampled)
kernels sharp-lanczos3 x 14.82 ops/sec ±0.92% (69 runs sampled)
 png sharp-buffer-file x 9.64 ops/sec ±0.57% (48 runs sampled)
 png sharp-buffer-buffer x 9.56 ops/sec ±0.89% (48 runs sampled)
 png sharp-file-file x 9.36 ops/sec ±1.16% (47 runs sampled)
 png sharp-file-buffer x 9.64 ops/sec ±0.77% (49 runs sampled)
 png sharp-progressive x 6.61 ops/sec ±0.79% (35 runs sampled)
 png sharp-withoutAdaptiveFiltering x 10.28 ops/sec ±0.50% (51 runs sampled)
webp sharp-buffer-file x 9.34 ops/sec ±0.84% (47 runs sampled)
webp sharp-buffer-buffer x 9.36 ops/sec ±0.59% (47 runs sampled)
webp sharp-file-file x 9.30 ops/sec ±0.89% (47 runs sampled)
webp sharp-file-buffer x 9.26 ops/sec ±1.00% (47 runs sampled)
```

Only vips_resize
```
jpeg sharp-buffer-file x 14.60 ops/sec ±1.43% (68 runs sampled)
jpeg sharp-buffer-buffer x 14.79 ops/sec ±0.98% (69 runs sampled)
jpeg sharp-file-file x 14.32 ops/sec ±1.04% (67 runs sampled)
jpeg sharp-stream-stream x 14.03 ops/sec ±1.27% (66 runs sampled)
jpeg sharp-file-buffer x 14.32 ops/sec ±0.93% (67 runs sampled)
jpeg sharp-promise x 14.61 ops/sec ±0.96% (68 runs sampled)
operations sharp-sharpen-mild x 13.52 ops/sec ±0.88% (64 runs sampled)
operations sharp-sharpen-radius x 9.35 ops/sec ±1.10% (47 runs sampled)
operations sharp-blur-mild x 13.83 ops/sec ±1.09% (65 runs sampled)
operations sharp-blur-radius x 12.40 ops/sec ±1.28% (59 runs sampled)
operations sharp-gamma x 5.23 ops/sec ±0.66% (29 runs sampled)
operations sharp-normalise x 8.90 ops/sec ±1.35% (45 runs sampled)
operations sharp-greyscale x 7.72 ops/sec ±0.82% (40 runs sampled)
operations sharp-greyscale-gamma x 2.89 ops/sec ±0.70% (19 runs sampled)
operations sharp-progressive x 12.43 ops/sec ±0.87% (59 runs sampled)
operations sharp-without-chroma-subsampling x 13.70 ops/sec ±0.81% (64 runs sampled)
operations sharp-rotate x 13.96 ops/sec ±0.87% (66 runs sampled)
operations sharp-without-simd x 10.94 ops/sec ±0.86% (53 runs sampled)
operations sharp-sequentialRead x 14.52 ops/sec ±1.06% (68 runs sampled)
operations sharp-crop-entropy x 14.81 ops/sec ±1.12% (69 runs sampled)
operations sharp-crop-attention x 14.81 ops/sec ±1.00% (69 runs sampled)
kernels sharp-cubic x 15.24 ops/sec ±1.02% (70 runs sampled)
kernels sharp-lanczos2 x 14.86 ops/sec ±0.97% (69 runs sampled)
kernels sharp-lanczos3 x 14.78 ops/sec ±1.04% (69 runs sampled)
 png sharp-buffer-file x 9.52 ops/sec ±0.89% (48 runs sampled)
 png sharp-buffer-buffer x 9.63 ops/sec ±0.70% (48 runs sampled)
 png sharp-file-file x 9.60 ops/sec ±0.56% (48 runs sampled)
 png sharp-file-buffer x 9.61 ops/sec ±0.53% (48 runs sampled)
 png sharp-progressive x 6.59 ops/sec ±0.57% (35 runs sampled)
 png sharp-withoutAdaptiveFiltering x 10.19 ops/sec ±1.07% (51 runs sampled)
webp sharp-buffer-file x 9.36 ops/sec ±0.73% (47 runs sampled)
webp sharp-buffer-buffer x 9.40 ops/sec ±0.81% (47 runs sampled)
webp sharp-file-file x 9.36 ops/sec ±0.84% (47 runs sampled)
webp sharp-file-buffer x 9.31 ops/sec ±0.76% (47 runs sampled)
```

Both changes: vips_resize, lower factor for shrinkOnLoad:
```
jpeg sharp-buffer-file x 5.74 ops/sec ±0.84% (32 runs sampled)
jpeg sharp-buffer-buffer x 5.78 ops/sec ±0.64% (32 runs sampled)
jpeg sharp-file-file x 5.74 ops/sec ±0.55% (32 runs sampled)
jpeg sharp-stream-stream x 5.68 ops/sec ±0.87% (31 runs sampled)
jpeg sharp-file-buffer x 5.74 ops/sec ±0.56% (31 runs sampled)
jpeg sharp-promise x 5.81 ops/sec ±0.56% (32 runs sampled)
operations sharp-sharpen-mild x 5.60 ops/sec ±0.80% (31 runs sampled)
operations sharp-sharpen-radius x 4.80 ops/sec ±0.90% (27 runs sampled)
operations sharp-blur-mild x 5.65 ops/sec ±0.68% (31 runs sampled)
operations sharp-blur-radius x 5.40 ops/sec ±0.81% (30 runs sampled)
operations sharp-gamma x 5.20 ops/sec ±0.73% (29 runs sampled)
operations sharp-normalise x 3.63 ops/sec ±0.68% (22 runs sampled)
operations sharp-greyscale x 3.03 ops/sec ±0.86% (19 runs sampled)
operations sharp-greyscale-gamma x 2.89 ops/sec ±0.83% (18 runs sampled)
operations sharp-progressive x 5.36 ops/sec ±0.78% (30 runs sampled)
operations sharp-without-chroma-subsampling x 5.63 ops/sec ±0.58% (31 runs sampled)
operations sharp-rotate x 5.33 ops/sec ±0.72% (30 runs sampled)
operations sharp-without-simd x 5.36 ops/sec ±0.72% (30 runs sampled)
operations sharp-sequentialRead x 6.16 ops/sec ±0.85% (33 runs sampled)
operations sharp-crop-entropy x 5.80 ops/sec ±0.57% (32 runs sampled)
operations sharp-crop-attention x 5.77 ops/sec ±0.59% (32 runs sampled)
kernels sharp-cubic x 5.99 ops/sec ±0.59% (33 runs sampled)
kernels sharp-lanczos2 x 5.89 ops/sec ±0.79% (32 runs sampled)
kernels sharp-lanczos3 x 5.75 ops/sec ±0.62% (32 runs sampled)
 png sharp-buffer-file x 9.55 ops/sec ±0.72% (48 runs sampled)
 png sharp-buffer-buffer x 9.65 ops/sec ±0.54% (48 runs sampled)
 png sharp-file-file x 9.59 ops/sec ±0.65% (48 runs sampled)
 png sharp-file-buffer x 9.67 ops/sec ±0.57% (48 runs sampled)
 png sharp-progressive x 6.61 ops/sec ±0.75% (35 runs sampled)
 png sharp-withoutAdaptiveFiltering x 10.31 ops/sec ±0.48% (51 runs sampled)
webp sharp-buffer-file x 9.25 ops/sec ±1.02% (47 runs sampled)
webp sharp-buffer-buffer x 9.35 ops/sec ±0.87% (47 runs sampled)
webp sharp-file-file x 9.34 ops/sec ±0.94% (47 runs sampled)
webp sharp-file-buffer x 9.35 ops/sec ±0.82% (47 runs sampled)

```

**Comment by lovell** [comment]
Sorry for the delay in responding Jarda, I've finally made time to look this PR and think about it properly. 

Switching from shrink+reduce to use resize only seems like an excellent thing to do so if you're still game let's go for it!

In terms of shrink-on-load behaviour, I definitely prefer the dynamic approach suggested here instead of PR #956.

I'd quite like this part of the change in behaviour to be configurable as the current faster approach seems to work for most people most of the time. This might be via something like:

```javascript
resize(width, height, { shrinkOnLoad: false })
```

where `shrinkOnLoad` defaults to true.

Did you see the v0.19.0 `suit`  work-in-progress branch? It may contain changes that conflict here so perhaps targeting that branch (which is waiting for libvips v8.6.0 before I merge it to master).

Thanks again for working on this, your time is much appreciated!

**Comment by lovell** [comment]
Sorry, I meant something like `lessShrinkOnLoad` for the option.

```sh
resize(width, height, { lessShrinkOnLoad: true })
```

Not sure about that name though; need to think some more.

**Comment by lovell** [comment]
The upsampling-only `interpolator` property of sharp's `resize()` operation can be removed as libvips selects one for you based on the `kernel` property. (You may already have spotted this.)

**Comment by jardakotesovec** [comment]
@lovell Great, thanks for feedback, will aim to make progress on that later today or tomorrow.

**Comment by jardakotesovec** [comment]
@lovell Should work on the vips_resize and shrinkOnLoad in separate PRs?

**Comment by lovell** [comment]
@jardakotesovec Entirely up to you. The vips_resize change will need to go in a major release, so perhaps focus on this first given libvips v8.6.0 and sharp v0.19.0 are likely in the next few weeks.

I submitted a small change to libvips to help enable this work too - see https://github.com/jcupitt/libvips/commit/ea6d496484ec212e93353988917706dbd7bed435

**Comment by jardakotesovec** [comment]
@lovel Ok. Just question - 8.6.0 release https://github.com/lovell/sharp-libvips/releases still has 8.5.8 version. So it fails on version check both on build and runtime. Is that intended for time being and I have to manually adjust the versions?

**Comment by lovell** [comment]
libvips v8.6.0 isn't published yet so if you're on OS X you'll need to install libvips from source using its master branch.

The pre-release Linux and Windows tarballs should be OK, at least according to the CI jobs.

https://travis-ci.org/lovell/sharp/builds/282365910
https://ci.appveyor.com/project/lovell/sharp/build/902

**Comment by jardakotesovec** [comment]
Closing this in favor of #977

**Pull request closed without merging**
