### PR TITLE
fix rotate/extract ordering for non-90 angles

### LINKED ISSUE #1682: Rotation angles that are not multiples of 90 ignore operation ordering
```
521   System:
522     OS: macOS High Sierra 10.13.6
523     CPU: (4) x64 Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
524     Memory: 82.42 MB / 8.00 GB
525     Shell: 3.2.57 - /bin/bash
526   Binaries:
527     Node: 10.9.0 - ~/.nvm/versions/node/v10.9.0/bin/node
528     Yarn: 1.12.3 - ~/.yarn/bin/yarn
529     npm: 6.2.0 - ~/.nvm/versions/node/v10.9.0/bin/npm
530     Watchman: 4.9.0 - /usr/local/bin/watchman
531   Utilities:
532     CMake: 3.8.2 - /usr/local/bin/cmake
533     Make: 3.81 - /usr/bin/make
534     GCC: 4.2.1 - /usr/bin/gcc
535     Git: 2.13.2 - /usr/local/bin/git
536   Languages:
537     Bash: 3.2.57 - /bin/bash
538     Go: 1.8.3 - /usr/local/bin/go
539     Java: 1.8.0_77 - /usr/bin/javac
540     Perl: 5.18.2 - /usr/bin/perl
541     PHP: 7.1.23 - /usr/bin/php
542     Python: 2.7.12 - /Users/iovdin/projects/miniconda2/bin/python
543     Ruby: 2.3.7p456 - /usr/bin/ruby
544     Rust: 1.28.0 - /usr/local/bin/rustc
```

running this code
```javascript
const fs = require('fs');
const sharp = require('sharp');
const https = require('https');

const picUrl = "https://www.cosy.sbg.ac.at/~pmeerw/Watermarking/lena_color.gif"

const pipeline = sharp()
  .rotate(45)
  .extract({ left: 100, top: 100, width: 312, height: 312 })

https.get(picUrl, (res) => {
  res.pipe(pipeline);
  pipeline.pipe(fs.createWriteStream('out.jpg'))
})
```

Both rotate, extract and extract, rotate order gives the same result image

What is the expected behaviour?
After the rotation, I'd expect extract work with rotated image

### PR DESCRIPTION
**Pull request by iovdin**
Fixes #1682.
Without refactoring as noted in the issue

### CODE REVIEW

**Comment by lovell** [comment]
Hi, thanks for this. Are you able to add a unit test or two that would previously have failed. There is a linter error to deal with also.

**Comment by iovdin** [comment]
will do

**Comment by iovdin** [comment]
@lovell Does it looks good enough?

**Comment by lovell** [comment]
Sorry, I somehow missed the update notifications for this - will take a look tomorrow - thanks again for fixing it.

**Comment by lovell** [comment]
Thanks for fixing the linter error and adding tests. Are you able to move the copy/pasted section of code that performs the rotation into a common `Rotate` function in the operations.cc file?

**Comment by lovell** [comment]
Thanks for this PR and for bearing with me whilst I prepared the rest of the next release. This will be in v0.23.0.

**Pull request merged**
