### PR TITLE
Allow overlayWith source without an alpha channel #506

### PR DESCRIPTION
**Pull request by cmtt**
These changes allow to composite opaque images, applying the commit @strarsis has mentioned.

### CODE REVIEW

**Comment by lovell** [comment]
Hello, thanks for this PR. Looks great - always a pleasure to see tests too.

I'll merge this after I've got the v0.16.0 work-in-progress "pencil" branch into master, probably later this week.

**Comment by cmtt** [comment]
Hello Lovell,

thank you for the great effort!

I additionally allowed myself to change the list of contributors.

**Comment by lovell** [comment]
Hello Matthias, please can you rebase against the recently updated `upstream/master` branch and add the `sharp` namespace to the `Is16Bit` call.

**Comment by cmtt** [comment]
Hello Lovell, this PR was rebased against `upstream/master` and applies the aforementioned change.

**Comment by lovell** [comment]
@cmtt It looks like you may have merged rather than rebased (e.g. the PR shouldn't contain my commits).

**Comment by cmtt** [comment]
Hello Lovell, thanks for the heads up. The PR has been updated.

**Comment by lovell** [comment]
Great, thank you Matthias.

**Pull request merged**
