### PR TITLE
Added support for Tinting images using a colour

### PR DESCRIPTION
**Pull request by rikh42**
This works in a similar way to the Photoshop Colour Blend mode, as it preserves the image luminance, while tinting it with the specified colour.

### CODE REVIEW

**Comment by lovell** [comment]
Hi Rik, thanks for this, I'll take a closer look at it tomorrow. Are you able to rebase against upstream/master to remove the extraneous commits?

**Comment by lovell** [comment]
I've just spotted the target branch is `ridge`. This has now been merged into `master` ahead of v0.18.0.

Are you able to change this PR to  target `master`?

(Last time I checked there was a limitation of Github that required opening a new one to switch destination branches.)

**Comment by lovell** [comment]
Looks like removing the `ridge` branch closed this PR automagically - please can you open a new one.

**Comment by rikh42** [comment]
Sure. I'll try and figure out the rebasing magic too.

**Pull request closed without merging**
